version: '3.8'

services:
  web:
    build: .
    # This runs your Django server
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  # Redis (Required for Channels & Celery)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Celery Worker (The Auto-Cancel Timer)
  celery:
    build: .
    # UPDATED LINE BELOW: We changed 'project_name' to 'config'
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  # Postgres Database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  postgres_data: