# Generated by Django 5.2.8 on 2025-11-25 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_order', models.IntegerField(default=1)),
                ('grid_cols', models.IntegerField(default=12, editable=False)),
                ('total_rows', models.IntegerField(default=20)),
            ],
            options={
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_bookable', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=1)),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SeatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('total_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=12, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('linked_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('col_index', models.PositiveIntegerField()),
                ('row_span', models.PositiveIntegerField(default=1)),
                ('col_span', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=50)),
                ('seat_identifier', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='admin_panel.deck')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.seatcategory')),
                ('features', models.ManyToManyField(blank=True, to='admin_panel.seatfeature')),
            ],
            options={
                'unique_together': {('deck', 'row_index', 'col_index')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='admin_panel.ship'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('LOCKED', 'Temporary Hold'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='LOCKED', max_length=20)),
                ('lock_created_at', models.DateTimeField(auto_now_add=True)),
                ('lock_expires_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin_panel.booking')),
                ('seat_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.layoutobject')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.route')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.ship')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.trip'),
        ),
        migrations.CreateModel(
            name='TripPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seatcategory')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='admin_panel.trip')),
            ],
            options={
                'unique_together': {('trip', 'seat_category')},
            },
        ),
    ]
