# Generated by Django 5.2.8 on 2025-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='icon_slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deck',
            name='total_rows',
            field=models.IntegerField(default=20, help_text='Current rows in the grid'),
        ),
    ]
