# Generated by Django 5.2.8 on 2025-11-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_seatcategory_description_seatcategory_icon_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='grid_cols',
            field=models.IntegerField(default=24, editable=False),
        ),
    ]
