# Generated by Django 5.2.8 on 2025-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_deck_grid_cols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='grid_cols',
            field=models.IntegerField(default=24),
        ),
    ]
