# Generated by Django 5.2.8 on 2025-12-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_deck_grid_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='sales_channel',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COUNTER', 'Counter')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.counter'),
        ),
        migrations.AddField(
            model_name='counter',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='admin_panel.location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_ending', to='admin_panel.location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_starting', to='admin_panel.location'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('time_offset_minutes', models.PositiveIntegerField(default=0, help_text='Minutes from start')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='admin_panel.route')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='trippricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='from_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_starting', to='admin_panel.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='to_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_ending', to='admin_panel.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trippricing',
            name='from_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_starts', to='admin_panel.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trippricing',
            name='to_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_ends', to='admin_panel.routestop'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='trippricing',
            unique_together={('trip', 'seat_category', 'from_stop', 'to_stop')},
        ),
    ]
