# Generated by Django 5.2.8 on 2025-12-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_district_division_location_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegmentPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_prices_starts', to='admin_panel.routestop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_prices', to='admin_panel.route')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seatcategory')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_prices_ends', to='admin_panel.routestop')),
            ],
            options={
                'unique_together': {('route', 'seat_category', 'from_stop', 'to_stop')},
            },
        ),
    ]
