# Generated by Django 5.2.8 on 2025-12-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_routesegmentpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human readable name (e.g., 'Double Bed')", max_length=50)),
                ('iconify_code', models.CharField(help_text="The Iconify string (e.g., 'mdi:bed-double-outline')", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seatcategory',
            name='icon_slug',
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Select the icon to display on the booking grid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='admin_panel.seaticon'),
        ),
    ]
