# Generated by Django 5.2.8 on 2025-12-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_seaticon_remove_seatcategory_icon_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Global multiplier for this trip (e.g., 1.5 for Eid holiday)', max_digits=4),
        ),
    ]
