# Generated by Django 5.2.8 on 2025-12-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_trip_price_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The actual price the user paid/will pay at the time of booking.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='admin_panel.trip'),
            preserve_default=False,
        ),
    ]
