# Generated by Django 5.2.8 on 2025-12-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_counter_created_at_alter_deck_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layoutobject',
            unique_together={('deck', 'row_index', 'col_index')},
        ),
        migrations.AddField(
            model_name='trip',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Set to False to hide this specific date from customers'),
        ),
        migrations.AlterField(
            model_name='layoutobject',
            name='seat_identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='layoutobject',
            unique_together={('deck', 'row_index', 'col_index'), ('deck', 'seat_identifier')},
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(help_text='Standard daily departure time')),
                ('is_active', models.BooleanField(default=True)),
                ('advance_booking_days', models.PositiveIntegerField(default=10)),
                ('run_monday', models.BooleanField(default=True)),
                ('run_tuesday', models.BooleanField(default=True)),
                ('run_wednesday', models.BooleanField(default=True)),
                ('run_thursday', models.BooleanField(default=True)),
                ('run_friday', models.BooleanField(default=True)),
                ('run_saturday', models.BooleanField(default=True)),
                ('run_sunday', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.route')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.ship')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_trips', to='admin_panel.tripschedule'),
        ),
    ]
