# Generated by Django 5.2.8 on 2026-01-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_layoutobject_unique_together_trip_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Standard arrival time', null=True),
        ),
        migrations.AlterField(
            model_name='tripschedule',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Standard daily departure time', null=True),
        ),
    ]
