# Generated by Django 5.2.8 on 2026-01-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_trip_arrival_datetime_tripschedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ABOUT US', max_length=200)),
                ('background_image', models.ImageField(help_text='Upload the top banner background image', upload_to='about/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Story', help_text='Small text above title', max_length=100)),
                ('title', models.CharField(default='Discover the World with Confidence', max_length=200)),
                ('description', models.TextField(help_text='The main paragraph text')),
                ('story_image', models.ImageField(help_text='The image on the right side', upload_to='about/story/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Blog', max_length=200)),
                ('background_image', models.ImageField(help_text='Upload the top banner image (e.g., 1920x400)', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Page Banner',
                'verbose_name_plural': 'Blog Page Banners',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog/')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('read_time', models.CharField(default='2 Min Read', help_text="e.g. '5 Min Read'", max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', help_text="The main title like 'Contact Us'", max_length=200)),
                ('background_image', models.ImageField(help_text='Upload the breadcrumb background image', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '1. Contact Page Banner',
                'verbose_name_plural': '1. Contact Page Banners',
            },
        ),
        migrations.CreateModel(
            name='ContactFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Have questions?', max_length=200)),
                ('side_image', models.ImageField(help_text='The image on the left side', upload_to='contact/faq/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='contact_icons/')),
                ('description', models.TextField(help_text='The small gray text description')),
                ('contact_info', models.CharField(blank=True, help_text='The email, phone number, or link text. Leave empty for Location cards.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_embed_code', models.TextField(help_text='Paste the full <iframe> code from Google Maps here.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/main/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Gallery', max_length=100)),
                ('title', models.CharField(default='Experience Through Images', max_length=200)),
                ('description', models.TextField(default='Discover some of our finest work captured through visuals')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gateway to Global Tours', max_length=255)),
                ('description', models.TextField(default='Discover exclusive travel packages...')),
                ('logo', models.FileField(help_text='Upload SVG or PNG', upload_to='banner/logos/')),
                ('background_image', models.ImageField(upload_to='banner/bg/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banner',
            },
        ),
        migrations.CreateModel(
            name='SeasonalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Featured Tours', max_length=100)),
                ('title', models.CharField(default='Discover Extraordinary Seasonal Specials', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 7 Days in Bali Paradise', max_length=200)),
                ('image', models.ImageField(upload_to='gallery/tours/')),
                ('link', models.CharField(default='#', help_text='Link to tour details page', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload your website logo', upload_to='site_identity/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_panel.blogpost')),
            ],
        ),
    ]
