# Generated by Django 5.2.8 on 2026-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_aboutbanner_aboutstory_blogbanner_blogpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to MK Shipping Lines', max_length=200)),
                ('description', models.TextField(help_text='The main paragraph text.')),
                ('key_points', models.TextField(help_text=' The list of key highlights (bullet points).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_overview/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Overview',
                'verbose_name_plural': 'Home Overview',
            },
        ),
    ]
