# Generated by Django 5.2.8 on 2026-01-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_aboutbanner_aboutstory_blogbanner_blogpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
