# Generated by Django 5.2.8 on 2026-01-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_companyoverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstory',
            name='subtitle',
            field=models.CharField(blank=True, default='Our Story', help_text='Small text above title', max_length=100, null=True),
        ),
    ]
