# Generated by Django 5.2.8 on 2026-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_alter_ticket_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.layoutobject'),
        ),
    ]
