# Generated by Django 5.2.8 on 2026-01-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_ticket_seat_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.trip'),
        ),
    ]
