# Generated by Django 5.2.8 on 2026-01-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_booking_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='from_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_starting', to='admin_panel.routestop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_ending', to='admin_panel.routestop'),
        ),
    ]
