# Generated by Django 5.2.8 on 2026-01-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_ticket_from_stop_alter_ticket_to_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.trip'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_starting', to='admin_panel.routestop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.layoutobject'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_ending', to='admin_panel.routestop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='admin_panel.trip'),
        ),
    ]
