# Generated by Django 5.2.8 on 2026-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='image',
            field=models.ImageField(blank=True, help_text='Ship image (size: 275x145 pixels)', null=True, upload_to='ships/'),
        ),
    ]
