# Generated by Django 5.2.8 on 2026-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_ship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expiry_at',
            field=models.DateTimeField(blank=True, help_text='Auto-cancel time for unpaid bookings', null=True),
        ),
    ]
