# Generated by Django 5.2.8 on 2026-01-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_booking_expiry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_snapshot',
            field=models.CharField(blank=True, help_text='Stores seat numbers for expired bookings', max_length=255, null=True),
        ),
    ]
