# Generated by Django 5.2.8 on 2026-02-17 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_booking_trip_alter_ticket_from_stop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds_from', to='admin_panel.routestop')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
                ('seat_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='admin_panel.layoutobject')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds_to', to='admin_panel.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='admin_panel.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trip', 'from_stop', 'to_stop', 'seat_object'), name='uniq_seat_hold_per_segment')],
            },
        ),
    ]
