# Generated by Django 5.2.8 on 2026-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_seathold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seathold',
            name='holder',
        ),
        migrations.AddField(
            model_name='seathold',
            name='holder_id',
            field=models.CharField(db_index=True, default=1, max_length=64),
            preserve_default=False,
        ),
    ]
