# Generated by Django 5.2.8 on 2026-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_remove_seathold_holder_seathold_holder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
