# Generated by Django 5.2.8 on 2026-02-24 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_booking_paid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staff user who created the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CounterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='admin_panel.counter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('counter', 'user')},
            },
        ),
    ]
