# Generated by Django 5.2.8 on 2026-02-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_booking_issued_by_counteruser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff user who created this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
