# Generated by Django 5.2.8 on 2026-02-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_alter_booking_issued_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passenger',
            name='uniq_passenger_per_booking_user',
        ),
    ]
