# Generated by Django 5.2.8 on 2026-03-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_booking_payment_date_booking_payment_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking_pdfs/'),
        ),
    ]
