# Generated by Django 5.2.8 on 2026-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_booking_qr_image_booking_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking_close_offset_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before departure when booking closes for this trip. Leave blank to inherit from schedule/default.', null=True),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='booking_close_offset_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Default minutes before departure when booking closes. Leave blank to use default 5 minutes.', null=True),
        ),
    ]
