# Generated by Django 5.2.8 on 2026-03-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0042_trip_booking_close_offset_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., MV Grand Aqua)', max_length=100)),
                ('slug', models.SlugField(help_text='Used for the URL (e.g., mv-grand-aqua)', max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='E.g., The Queen of the River', max_length=200)),
                ('short_description', models.TextField(help_text='Brief summary for list/grid views', max_length=500)),
                ('full_description', models.TextField(help_text='Detailed description for the main vessel page')),
                ('hero_image', models.ImageField(upload_to='vessel_showcase/heroes/')),
                ('video_tour_url', models.URLField(blank=True, help_text='YouTube or Vimeo link for a virtual tour')),
                ('build_year', models.CharField(blank=True, max_length=4)),
                ('length_meters', models.CharField(blank=True, help_text='E.g., 85m', max_length=20)),
                ('top_speed', models.CharField(blank=True, help_text='E.g., 15 Knots', max_length=50)),
                ('display_capacity', models.CharField(blank=True, help_text='E.g., 500+ Passengers', max_length=50)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_cafe_bar', models.BooleanField(default=False)),
                ('has_prayer_room', models.BooleanField(default=False)),
                ('has_medical_facility', models.BooleanField(default=False)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('has_kids_play_area', models.BooleanField(default=False)),
                ('has_entertainment', models.BooleanField(default=False, help_text='Live music, TV lounges, etc.')),
                ('is_published', models.BooleanField(default=True, help_text='Show on the public website')),
                ('is_upcoming', models.BooleanField(default=False, help_text="Flag as 'Coming Soon'")),
                ('launch_date', models.DateField(blank=True, help_text='Expected launch date if upcoming', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.OneToOneField(blank=True, help_text='Leave blank if this vessel is not yet operational/bookable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase', to='admin_panel.ship')),
            ],
        ),
        migrations.CreateModel(
            name='CabinShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., VIP Balcony Suite', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='E.g., Ultimate comfort with a private view', max_length=150)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='cabin_showcase/covers/')),
                ('video_tour_url', models.URLField(blank=True, help_text='YouTube or Vimeo link')),
                ('guest_capacity', models.CharField(help_text='E.g., 2 Adults, 1 Child', max_length=50)),
                ('room_size', models.CharField(blank=True, help_text='E.g., 250 sq. ft.', max_length=50)),
                ('bed_type', models.CharField(blank=True, help_text='E.g., 1 King Bed or 2 Twin Beds', max_length=100)),
                ('view_type', models.CharField(blank=True, help_text='E.g., River View, Interior, Forward-facing', max_length=100)),
                ('is_air_conditioned', models.BooleanField(default=True)),
                ('has_attached_washroom', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_mini_fridge', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('has_room_service', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which cabins appear on the vessel page')),
                ('is_published', models.BooleanField(default=True)),
                ('is_sold_out_badge', models.BooleanField(default=False, help_text='Manually flag as High Demand or Sold Out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operational_categories', models.ManyToManyField(blank=True, help_text='Link to the actual bookable categories in the system.', related_name='showcases', to='admin_panel.seatcategory')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='admin_panel.vesselshowcase')),
            ],
            options={
                'ordering': ['vessel', 'display_order'],
            },
        ),
    ]
