# Generated by Django 5.2.8 on 2026-03-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_vesselshowcase_cabinshowcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinshowcase',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Select the operational features (e.g., AC, River Side) that apply to this cabin class.', related_name='showcases', to='admin_panel.seatfeature'),
        ),
        migrations.AlterField(
            model_name='cabinshowcase',
            name='vessel',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this to a specific vessel, or leave blank to use as a generic cabin/seat type across the fleet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabins', to='admin_panel.vesselshowcase'),
        ),
    ]
