# Generated by Django 5.2.8 on 2026-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_cabinshowcase_features_alter_cabinshowcase_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinshowcase',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='vesselshowcase',
            name='name',
            field=models.CharField(help_text='Display name (e.g., Carnival Cruise)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vesselshowcase',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated if left blank. Used for the URL (e.g., mv-grand-aqua)', max_length=120, unique=True),
        ),
    ]
