# Generated by Django 5.2.8 on 2026-03-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_alter_cabinshowcase_slug_alter_vesselshowcase_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The headline or title of the article.', max_length=255)),
                ('organization_name', models.CharField(help_text='Name of the publisher or newspaper (e.g., Forbes, TechCrunch).', max_length=255)),
                ('logo', models.ImageField(help_text='The logo of the organization.', upload_to='featured_articles/logos/')),
                ('description', models.TextField(help_text='A short excerpt, quote, or summary of the article.')),
                ('url', models.URLField(help_text='The direct link to the published article.', max_length=500)),
                ('article_identifier', models.SlugField(blank=True, help_text='Unique identifier/slug. Auto-generates from the name if left blank.', max_length=255, unique=True)),
                ('publication_date', models.DateField(blank=True, help_text='The official date the article was published.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the article from the live website without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Article',
                'verbose_name_plural': 'Featured Articles',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
