# Generated by Django 5.2.8 on 2026-04-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_featuredarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='admin_panel.route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='admin_panel.ship'),
        ),
    ]
