# Generated by Django 5.2.8 on 2026-04-04 09:20

import admin_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GET CONNECTED, PRICING, COMPANY', max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the left-to-right display order.')),
            ],
            options={
                'verbose_name': 'Footer Column',
                'verbose_name_plural': 'Footer Columns',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Submenu link text. Maximum 2 words.', max_length=50, null=True, validators=[admin_panel.models.validate_max_two_words])),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer/images/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='footer/banners/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the top-to-bottom display order.')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='admin_panel.footercolumn')),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Contents',
                'ordering': ['order', 'id'],
            },
        ),
    ]
