# Generated by Django 5.2.8 on 2026-04-04 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0050_footercolumn_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='url',
            field=models.CharField(default=1, help_text="The relative URL path starting with '/'.", max_length=255, validators=[django.core.validators.RegexValidator(message='URL must start with a forward slash (e.g., /about-us)', regex='^/')]),
            preserve_default=False,
        ),
    ]
