# Generated by Django 5.2.8 on 2026-04-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_footercontent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselshowcase',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image (4:1 ratio)', null=True, upload_to='vessel_showcase/banners/'),
        ),
    ]
