# Generated by Django 5.2.8 on 2026-04-08 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0054_cabinshowcase_banner_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff user who created this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff user who issued this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
