# Generated by Django 5.2.8 on 2026-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_booking_cancelled_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_view_trip_sheet', 'Can view trip sheet'), ('can_export_trip_sheet', 'Can export trip sheet')]},
        ),
    ]
