# Generated by Django 5.2.8 on 2026-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Temporary Hold'), ('BOOKED', 'Booked'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='LOCKED', max_length=20),
        ),
    ]
