# Generated by Django 5.2.8 on 2026-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0058_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
