# Generated by Django 5.2.8 on 2026-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0060_alter_ticket_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCommerzStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Admin friendly name (e.g. MV Greenline Payment Store)', max_length=100)),
                ('store_id', models.CharField(max_length=100, unique=True)),
                ('store_password', models.CharField(max_length=255)),
                ('is_live', models.BooleanField(default=False, help_text='False = Sandbox, True = Production')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SSLCommerz Store',
                'verbose_name_plural': 'SSLCommerz Stores',
            },
        ),
    ]
