# Generated by Django 5.2.8 on 2026-05-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0061_sslcommerzstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships', to='admin_panel.sslcommerzstore'),
        ),
    ]
