# Generated by Django 5.2.8 on 2026-05-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_ship_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gateway_type', models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sslcommerzstore',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sslcommerz_stores', to='admin_panel.paymentgateway'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=120, unique=True)),
                ('val_id', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('UNATTEMPTED', 'Unattempted')], default='PENDING', max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='admin_panel.booking')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.paymentgateway')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.sslcommerzstore')),
            ],
        ),
    ]
