# Generated by Django 5.2.8 on 2026-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_paymentgateway_booking_booking_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Payment Processing'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('LOCKED', 'Admin Locked')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('SSLCOMMERZ', 'SSLCommerz')], max_length=50, unique=True),
        ),
    ]
