# Generated by Django 5.2.8 on 2026-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0066_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_hold_minutes', models.PositiveIntegerField(default=5, help_text='Time in minutes seats are held before proceeding to payment.')),
                ('payment_timeout_minutes', models.PositiveIntegerField(default=5, help_text='Time in minutes allowed to complete the transaction on the payment gateway.')),
            ],
        ),
    ]
