# Generated by Django 5.2.8 on 2026-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0067_ticketsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.CharField(blank=True, help_text='Short remark to display on the trip sheet', max_length=30, null=True),
        ),
    ]
