# Generated by Django 5.2.8 on 2026-05-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0068_booking_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcategory',
            name='is_vehicle',
            field=models.BooleanField(default=False, help_text='Check this if this category represents a vehicle parking space (e.g., Sedan, Motorcycle).'),
        ),
        migrations.CreateModel(
            name='BookingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, help_text='e.g., Toyota Prado, Yamaha R15', max_length=150, null=True)),
                ('license_plate', models.CharField(help_text='e.g., Dhaka Metro-G-12-3456', max_length=100)),
                ('booking', models.ForeignKey(help_text='The parent booking this vehicle belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='admin_panel.booking')),
                ('ticket', models.OneToOneField(help_text='The specific layout slot/ticket assigned to this vehicle.', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='admin_panel.ticket')),
            ],
            options={
                'verbose_name': 'Booking Vehicle',
                'verbose_name_plural': 'Booking Vehicles',
            },
        ),
    ]
