# Generated by Django 5.2.8 on 2026-05-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0069_seatcategory_is_vehicle_bookingvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingvehicle',
            name='ticket',
            field=models.OneToOneField(blank=True, help_text='Linked after payment is confirmed. Null while booking is processing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='admin_panel.ticket'),
        ),
    ]
