# Generated by Django 5.2.8 on 2026-05-23 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0070_alter_bookingvehicle_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
