# Generated by Django 5.2.8 on 2026-01-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Customer'), (2, 'Staff')], default=2)),
                ('user_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended')], default=1)),
                ('balance', models.FloatField(default=0.0)),
                ('credit_limit', models.FloatField(default=0.0)),
                ('proxy_ip', models.GenericIPAddressField(blank=True, help_text="The IP of the Customer's VPS (Squid Proxy).", null=True, protocol='IPv4')),
                ('proxy_port', models.PositiveIntegerField(blank=True, default=3128, help_text='Default Squid port is 3128.', null=True)),
                ('proxy_username', models.CharField(blank=True, help_text='Optional: If you secure the Squid proxy with a password.', max_length=100, null=True)),
                ('proxy_password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='razer_users_groups', related_query_name='razer_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='razer_users_permissions', related_query_name='razer_user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
