# Generated by Django 5.2.8 on 2026-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True if the account was auto-created during booking and not yet claimed by the user.'),
        ),
    ]
