# Generated by Django 5.2.8 on 2026-02-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_guest'),
        ('admin_panel', '0037_booking_issued_by_counteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_counter',
            field=models.ForeignKey(blank=True, help_text='Counter this staff/admin user belongs to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='admin_panel.counter'),
        ),
    ]
