# Generated by Django 5.2.8 on 2026-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assigned_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Customer'), (2, 'Staff'), (3, 'Counter'), (4, 'Super Counter')], default=2),
        ),
    ]
